#生产环境配置

#port
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

# 日志配置 
logging:
  config: classpath:log4j2.yml

#spring 
spring:
  #--------------------------charset--------------------------
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
  #静态资源配置
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB    
  
  #thymeleaf模版引擎  
  thymeleaf:
    prefix: classpath:/templates/  #prefix：指定模板所在的目录 默认：/templates/
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix:  .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5

  #时间戳统一转换 
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss 
    time-zone: GMT+8
  
  #jdbc数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: 123456
#    url: jdbc:mysql://127.0.0.1:3306/yjbs?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8

    password: fx123456.        #Fx778899asdZ
    url: jdbc:mysql://121.37.161.108:3306/yjbs_test?sslmode=require&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    
    druid:
      initialSize: 1 #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      minIdle: 1  #最小连接池数量
      maxActive: 20 #最大连接池数量
      maxWait: 60000 #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true  #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。5.5及以上版本有PSCache，建议开启。
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall  #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat，日志用的filter:log4j， 防御sql注入的filter:wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      stat-view-servlet:
#        allow: 47.111.96.214

  #redis缓存配置
  redis:
    host: 127.0.0.1       #Redis 服务器地址
    port: 6379            #Redis 服务器连接端口
    timeout: 6000         #连接超时时间 单位 ms（毫秒）
#    password: qfc120      #设置密码防止攻击更安全
    password: fx123456.   #设置密码防止攻击更安全

  #jpa数据持久层
  jpa: 
    hibernate:
      ddl-auto: update #是否自动建表
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect #方言
        show-sql: false #是否自动打印sql语句
        format-sql: true #是否格式化sql语句
        #事务交由spring管理
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext


  
  
 
    